name: poly_scheduler
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.0
  http: ^1.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  bloc_concurrency: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/icons/drag_icon.png
    - assets/icons/1.5x/drag_icon.png
    - assets/icons/2.0x/drag_icon.png
    - assets/icons/3.0x/drag_icon.png
    - assets/icons/mingcute_sad-line.png
