name: poly_scheduler
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.0
  http: ^1.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.1.11

flutter:
  uses-material-design: true
  assets: 
    - assets/icons/drag_icon.png
    - assets/icons/1.5x/drag_icon.png
    - assets/icons/2.0x/drag_icon.png
    - assets/icons/3.0x/drag_icon.png